name: Commit

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 8 * * 0' # Every Sunday at 8:30AM UTC (5:30AM EST)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v1
