name: Commit

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 8 * * 0' # Every Sunday at 8:30AM UTC (5:30AM EST)

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Empty commit - Action keepalive
        run: |
          git config --global user.email "boris-ning-usds@users.noreply.github.com"
          git config --global user.name "Boris Ning"
          git commit --allow-empty -m "keepalive action"
