name: Onceler Deploy

on:
  push:
    branches: [master]
  schedule:
    - cron: '30 9 * * 0' # Every Sunday at 9:30AM UTC (5:30AM EST)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby installation
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: false

      - name: Deploy to cloud.gov
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_api: ${{ secrets.CF_API }}
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: ${{ secrets.CF_ORG }}
          cf_space: ${{ secrets.CF_SPACE }}

      - name: Modify the README file
        run: |
          echo " " >> README.md

      - name: Commit CIDR changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Github Action Bot
          author_email: noreply@github.com
          message: 'Adding a space to ensure Github action continues working past 60 days of inactivity.'
          add: 'README.md'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
