name: Onceler Deploy

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 9 * * 0' # Every Sunday at 9:30AM UTC (5:30AM EST)

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Read access to the repository contents

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Setup ruby installation
        uses: ruby/setup-ruby@354a1ad156761f5ee2b7b13fa8e09943a5e8d252 # v1.229.0
        with:
          bundler-cache: false

      - name: Deploy to cloud.gov
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_api: ${{ secrets.CF_API }}
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: ${{ secrets.CF_ORG }}
          cf_space: ${{ secrets.CF_SPACE }}

      - name: Notify slack channel
        uses: rtCamp/action-slack-notify@c33737706dea87cd7784c687dadc9adf1be59990 # v2.3.2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MSG_AUTHOR: usds-bot
          SLACK_MESSAGE: 'GH Actions: deployed Onceler :rocket:'
          MSG_MINIMAL: true
