name: Onceler Deploy

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 9 * * 0' # Every Sunday at 9:30AM UTC (5:30AM EST)

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Read access to the repository contents

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup ruby installation
        uses: ruby/setup-ruby@09a7688d3b55cf0e976497ff046b70949eeaccfd # v1.288.0
        with:
          bundler-cache: false

      - name: Deploy to cloud.gov
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_api: ${{ secrets.CF_API }}
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: ${{ secrets.CF_ORG }}
          cf_space: ${{ secrets.CF_SPACE }}

      - name: Notify slack channel
        uses: rtCamp/action-slack-notify@e31e87e03dd19038e411e38ae27cbad084a90661 # v2.3.3
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MSG_AUTHOR: usds-bot
          SLACK_MESSAGE: 'GH Actions: deployed Onceler :rocket:'
          MSG_MINIMAL: true
